### PR TITLE
Turn the compiler into a protoc plugin

### PR DESCRIPTION
**Pull request by pbor**
Is there some reason I am missing to have a standalone "protoc-c" compiler instead of using a plugin as documented on the protobuf documentation? If it is just an historical artifact, I think we should change... or maybe to simply have both binaries (they are just 3 lines of code afterall)

I was surprised that changing the code to a plugin is very simple and the tests still pass.

If you agree with this, I'll try to spend some time also updating this PR to also fix the cmake build and the documentation etc.

### CODE REVIEW

**Comment by edmonds** [comment]
Hi, Paolo:

Very nice! I didn't realize it was this easy.

I would guess that the reason the `protobuf-c` compiler is a separate utility is because `protobuf-c` pre-dates the existence of the plugin support in the `protobuf` compiler. It looks like that feature was added in `protobuf` 2.3.0 (January 2010), and the first releases of `protobuf-c` date back to 2008.

However, your patch removes the `protoc-c` utility entirely, which would break all the `protobuf-c` users who currently call `protoc-c` from their build systems to compile `.proto` files. It might be suitable for a `protobuf-c` 2.0.0 release, but we should at least support both in `protobuf-c` 1.x for a while to give people time to migrate.

Could you update your patch to build both `protoc-c` and `protoc-gen-c`? Since the binary is fairly large (227 KB on my amd64 system, stripped), we might want to have a single binary support both behaviors, depending on whether it's called as "protoc-c" or "protoc-gen-c".

Thanks!

**Comment by pbor** [comment]
Note that it is mandatory that the binary is named like that..   I guess
the simplest way would be to make a simple wrapper script called protoc-c
that calls protoc with the right args.

The other way would be to install a symlink and then check argv 0 to
conditionally do one thing or the other
Il 10/Feb/2016 19:32, "Robert Edmonds" <notifications@github.com> ha
scritto:

**Comment by edmonds** [comment]
Yeah, the easiest thing to do is probably to check `argv[0]` and do the requested behavior, and install a symlink from `protoc-gen-c` to `protoc-c`.

**Comment by pbor** [comment]
Sorry for the delay, I updated the PR to install the symlink and behave in a backward compatible way when invoked as protoc-c.

I also updated the cmake build system (now "make test" passes also with cmake, before it was failing because one file was missing)

**Comment by pbor** [comment]
I also update the readme and license file. In the license file I only also specified protoc-gen-c for clarity

**Comment by zapstar** [comment]
@edmonds When will this get pulled into master? I would very much like to see this in the next release.

**Comment by edmonds** [comment]
Hi, Paolo:

I've merged this into the `next` branch (the `master` branch is for released code only), and it will be in the next release. Unfortunately GitHub doesn't let the PR recipient (or even the PR author) modify the target branch, so I'm just marking the PR closed.

Thanks!

**Pull request closed without merging**
