### PR TITLE
Bump version to 1.3.3

### PR DESCRIPTION
**Pull request by edmonds**

### CODE REVIEW

**Comment by lipnitsk** [comment]
@edmonds It would be good to include #378, #392, #400 in the 1.3.3 release. I can merge those branches and edit the ChangeLog if you would like.

**Comment by edmonds** [comment]
Thanks, I'll take a look at those PRs today.

**Comment by lipnitsk** [comment]
@edmonds ping, could you look at finalizing 1.3.3 sometime soon?

**Comment by edmonds** [comment]
:+1:

**Comment by lipnitsk** [comment]
@edmonds do you have an idea of when you'll get a chance to look at this?

**Comment by netrounds-fredrik** [comment]
It looks like this project needs some more maintainers. Is @edmonds currently the only one that can take care of PRs and make releases?

**Comment by lipnitsk** [comment]
I can *technically* do it, but @edmonds has been the one doing by our mutual agreement (and he has more packaging experience). @edmonds, if you are really busy, let me know if you want me to attempt a release.

**Pull request merged**
