### PR TITLE
Use standard BUILD_TESTING option for cmake

### PR DESCRIPTION
**Pull request by morrisonlevi**
You can see it in the docs here: https://cmake.org/cmake/help/latest/command/enable_testing.html.

### CODE REVIEW

**Comment by lipnitsk** [comment]
I don't know if it's really much of a standard, especially since we:
a. don't use CTest;
b. call enable_testing() ourselves anyway

Add to that forcing existing users to change their CMake invocation and the benefit of this change seems questionable at best. Based on the reasons above I'm gonna close this request.

**Comment by morrisonlevi** [comment]
There's not a release with the `BUILD_TESTS` value. Break... who?

**Comment by lipnitsk** [comment]
Fair enough, looks like it was introduced in e01b30d4fecf4de6a7983acf35dad8eea9b44666. But note that at least https://github.com/protobuf-c/protobuf-c/blob/next/.github/workflows/build.yml reference it, so please fix that too.

**Comment by morrisonlevi** [comment]
I'm closing this in favor of #472, which will probably rework testing a bit so it tests the CMake package in source tree as well as the installed form. Thanks for considering it!

**Pull request closed without merging**
