### PR TITLE
protoc-c: fix shared lib build on windows, migrate from Travis CI to GitHub Actions

### LINKED ISSUE #458: unresolved external symbol (CGenerator) with Visual Studio 2017
- compiled protobuf-3.15.0-rc2 with `-DBUILD_SHARED_LIBS=ON` (yes I must have a DLL build, not static)
- configured protobuf-c-1.3.3 with `ADD_DEFINITIONS(-DPROTOBUF_USE_DLLS)` in CMakeLists.txt, and set `-DBUILD_SHARED_LIBS=ON`
- compile (protobuf-c-1.3.3) fails, with 1 unresolved external symbol error message:
```
Creating library protoc-gen-c.lib and object protoc-gen-c.exp
main.cc.obj : warning LNK4217: locally defined symbol ??0CGenerator@c@compiler@protobuf@google@@QAE@XZ (public: __thiscall google::protobuf::compiler::c::CGenerator::CGenerator(void)) imported in function _main
main.cc.obj : warning LNK4217: locally defined symbol ??1CGenerator@c@compiler@protobuf@google@@UAE@XZ (public: virtual __thiscall google::protobuf::compiler::c::CGenerator::~CGenerator(void)) imported in function _main
c_generator.cc.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) const google::protobuf::compiler::c::CGenerator::`vftable'" (__imp_??_7CGenerator@c@compiler@protobuf@google@@6B@) referenced in function "public: __thiscall google::protobuf::compiler::c::CGenerator::CGenerator(void)" (??0CGenerator@c@compiler@protobuf@google@@QAE@XZ)
protoc-gen-c.exe : fatal error LNK1120: 1 unresolved externals
```

This appears similar to issue reported through https://github.com/protobuf-c/protobuf-c/issues/447

### PR DESCRIPTION
**Pull request by lipnitsk**
Fixes #458

@jmckenna if you can test this that would be great, then we can merge it into the next release

### CODE REVIEW

**Review by jmckenna — COMMENTED** [review]
tested branch `issue-458` locally here.  Verified.

**Comment by lipnitsk** [comment]
@jmckenna I spent quite a bit of time and got it working finally, at least according to GitHub Actions CI and their windows server 2019 platform. Can you see if these changes now work for you? All you should need to do is tell cmake to -DBUILD_SHARED_LIBS (and, of course, have protobuf built with shared libs as described [here](https://github.com/protocolbuffers/protobuf/tree/master/cmake#dlls-vs-static-linking))

**Comment by lipnitsk** [comment]
@edmonds would like to merge this when you get a chance.

**Comment by lipnitsk** [comment]
@msshapira maybe you can take a look at the cmake changes too.

**Comment by jmckenna** [comment]
> 
> 
> @jmckenna I spent quite a bit of time and got it working finally, at least according to GitHub Actions CI and their windows server 2019 platform. Can you see if these changes now work for you? All you should need to do is tell cmake to `-DBUILD_SHARED_LIBS=ON` (and, of course, have protobuf built with shared libs as described [here](https://github.com/protocolbuffers/protobuf/tree/master/cmake#dlls-vs-static-linking))

Thanks for implementing `PROTOBUF_USE_DLLS`, as I had done in my [pull request](https://github.com/protobuf-c/protobuf-c/pull/461), which was the missing key to make this work.  Confirmed here.  Thanks for adding Github Action CI test for this as well.  Hope this can be included in the next release.  Thanks!

**Review by jmckenna — DISMISSED** [review]

**Review by edmonds — APPROVED** [review]

**Pull request merged**
