### PR TITLE
fix invalid unsigned arithmetic.

### PR DESCRIPTION
**Pull request by ihsinme**
I believe your checks are not correct.
in my opinion they are equivalent to checks !=.
I suggest a simple fix.

### CODE REVIEW

**Comment by lipnitsk** [comment]
Do you have a test case or a better description of what the issue is?

**Comment by ihsinme** [comment]
Yes indeed.
I will try to describe in more detail.

**Comment by ihsinme** [comment]
```cpp
unsigned long A;

// A= 70; (A - 11) = 59; true
// A= 11; (A - 11) = 0; false
// A= 1; (A - 11) = 18446744073709551607; true
// A= 0; (A - 11) = 18446744073709551606; true
if (A - 11 > 0)
```
as you can see, this comparison is equivalent to `A! = 11`.

I hope so my train of thought will be clear.

**Comment by lipnitsk** [comment]
Seems like a benign overflow fix. But, please, fix your commit message to reflect your change. `Update protobuf-c.c` is not an acceptable commit message.

**Comment by ihsinme** [comment]
> Seems like a benign overflow fix. But, please, fix your commit message to reflect your change. `Update protobuf-c.c` is not an acceptable commit message.

Oh sure.
it's really not pretty (

**Comment by ihsinme** [comment]
I fixed the name of the commit.

**Review by edmonds — APPROVED** [review]

**Comment by savar** [comment]
sorry to comment on this merged one, but while it fixes a risky topic of copying data from somewhere to somehwere else (in case this sign issue leads to a huge number which still can be allocated) then you still have a weird wrong situation:

```c
    if (len > pref_len) {
      bd->data = do_alloc(allocator, len - pref_len);
      if (bd->data == NULL)
        return FALSE;
      memcpy(bd->data, data + pref_len, len - pref_len);
    } else {
      bd->data = NULL;
    }
    bd->len = len - pref_len;
    return TRUE;
```

the protobufcbinarydata will have a struct of NULL as data, a huge `->len` and it will return TRUE which seems totally off and wrong to me.

Do I miss something or should the `else {}` of the `if (len > pref_len)` not block this situation by also returning FALSE?
I might also miss one situation which IS actually okay, which would be `len == 0` but `pref_len > 0` but otherwise I don't understand right now why we could have a case where `bd-data = NULL` would be "okay" (or maybe it is, but then set the `->len` to `0` in the `else` and otherwise set it after the `memcpy` to the correct size).

**Pull request merged**
