### PR TITLE
Exclude downloaded protobuf from coveralls report

### PR DESCRIPTION
**Pull request by Sannis**

### CODE REVIEW

**Comment by lipnitsk** [comment]
Should we also exclude protoc-c from the coverage results?

**Comment by Sannis** [comment]
I sent this patch as the fist step. But initially I had different idea - include protoc-c code to coverage report.

**Comment by lipnitsk** [comment]
Good point, but we don't have any tests for protoc-c today. @edmonds, should we keep protoc-c in the code coverage report?

**Comment by lipnitsk** [comment]
I have pulled in your coveralls change, the language change doesn't seem to fix anything today so we can keep both c and cpp for now unless travis starts failing with our configuration.

**Pull request closed without merging**
