### PR TITLE
Support for new Google protobuf 22.x, 23.x releases

### PR DESCRIPTION
**Pull request by edmonds**
This branch implements support for the latest protobuf 22.x and 23.x releases while still maintaining backwards compatibility with previous protobuf releases. It looks like all we needed to do was build in C++17 mode on protobuf >= 4.22.0 and remove the `GOOGLE_*` macro invocations (or, rather, map them to their `ABSL_*` equivalents in later protobuf releases).

[edited out erroneous build results]

### CODE REVIEW

**Comment by edmonds** [comment]
OK, the cmake build doesn't like the `FileDescriptor::SYNTAX_PROTO3` thing, but the autotools build works fine :thinking: 

Ah, looks like we somehow lost `HAVE_PROTO3` in the autotools build. So I guess the build results above aren't particularly useful.

**Comment by carlocab** [comment]
To fix the CMake build, I think you need to change

https://github.com/protobuf-c/protobuf-c/blob/abc67a11c6db271bedbb9f58be85d6f4e2ea8389/build-cmake/CMakeLists.txt#L65

to something like

```cmake
FIND_PACKAGE(Protobuf REQUIRED CONFIG)
```
or, to try to maintain compatibility with older versions of Protobuf (e.g. one built using Autotools instead of CMake)
```cmake
FIND_PACKAGE(Protobuf REQUIRED CONFIG)
if(NOT Protobuf_FOUND)
  FIND_PACKAGE(Protobuf REQUIRED)
endif()
```
See https://github.com/protocolbuffers/protobuf/issues/12292.

**Comment by carlocab** [comment]
You may also need https://github.com/protobuf-c/protobuf-c/pull/555.

**Comment by edmonds** [comment]
Well, I got three very different CMake build failures on Debian unstable with protobuf 23.4 built from source, and the failures on CMake on OS X and Windows in CI. Looks like one of the failures might be https://github.com/protocolbuffers/protobuf/pull/13206.

Given that autotools is our primary build system and CMake is best effort, and protobuf/CMake seems to be in flux right now, I might merge this without also fixing CMake, which can get fixed later.

**Comment by jmckenna** [comment]
@edmonds I just tested this `new-google-support` branch with MSVC and CMake 3.26.4 :

Fatal error during compile:
```
[ 10%] Built target protobuf-c
CMakeFiles\protoc-gen-c.dir\build.make(405) : fatal error U1033: syntax error : '::' unexpected
Stop.
```
which refers to these lines in the generated `build.cmake`
```
protoc-gen-c.exe: protobuf::libprotoc-NOTFOUND
protoc-gen-c.exe: protobuf::libprotobuf-NOTFOUND
```
This is likely related to other upcoming CMake changes through #555 I imagine.   (darn, darn)

I'll have to go back to `protobuf-c-1.4.1` and `protobuf-3.19.4` until all of this is resolved, darn.

Please let me know if you need help testing all of this, when ready.

Apologies for me noise.

**Comment by edmonds** [comment]
> @edmonds I just tested this `new-google-support` branch with MSVC and CMake 3.26.4 :
> 
> Fatal error during compile:
> 
> ```
> [ 10%] Built target protobuf-c
> CMakeFiles\protoc-gen-c.dir\build.make(405) : fatal error U1033: syntax error : '::' unexpected
> Stop.
> ```
> 
> which refers to these lines in the generated `build.cmake`
> 
> ```
> protoc-gen-c.exe: protobuf::libprotoc-NOTFOUND
> protoc-gen-c.exe: protobuf::libprotobuf-NOTFOUND
> ```
> 
> This is likely related to other upcoming CMake changes through #555 I imagine. (darn, darn)
> 
> I'll have to go back to `protobuf-c-1.4.1` and `protobuf-3.19.4` until all of this is resolved, darn.
> 
> Please let me know if you need help testing all of this, when ready.
> 
> Apologies for my noise.

Thanks @jmckenna, looks like this is yet another CMake failure that I haven't seen before. Unfortunately I don't really know that much about CMake and Windows.

Could you clarify which commit of protobuf-c and which version of protobuf you tested with to get that failure? I'm guessing you tested the current tip of this branch (5b0661f1e8a0e03f75cc6f53b8d42507e95403c9) with protobuf 23.3 or 23.4?

**Comment by edmonds** [comment]
OK, with `FIND_PACKAGE(Protobuf REQUIRED CONFIG)`, the Windows build on protobuf 22 is definitely failing when we try to run cmake on the protobuf-c project with:

```
CMake Error at CMakeLists.txt:116 (GET_FILENAME_COMPONENT):
  GET_FILENAME_COMPONENT called with incorrect number of arguments
-- Configuring incomplete, errors occurred!
```

That line is:

```
GET_FILENAME_COMPONENT(PROTOBUF_DLL_DIR ${PROTOBUF_PROTOC_EXECUTABLE} DIRECTORY)
```

It also fails this way with slightly different capitalization:

```
GET_FILENAME_COMPONENT(PROTOBUF_DLL_DIR ${Protobuf_PROTOC_EXECUTABLE} DIRECTORY)
```

The error message from cmake sounds like `PROTOBUF_PROTOC_EXECUTABLE` / `Protobuf_PROTOC_EXECUTABLE` isn't getting set which makes me wonder if this is https://github.com/protocolbuffers/protobuf/pull/13206.

**Comment by edmonds** [comment]
Looks like https://github.com/protocolbuffers/protobuf/pull/13206 does indeed do something because now we have a different failure. This looks like the core part:

```
2023-07-08T01:03:22.6252828Z [  6%] Generating protobuf-c/protobuf-c.pb.cc, protobuf-c/protobuf-c.pb.h
2023-07-08T01:03:22.6510512Z 'cpp_out' is not recognized as an internal or external command,
2023-07-08T01:03:22.6511139Z operable program or batch file.
```

Full build log attached:

[build.txt](https://github.com/protobuf-c/protobuf-c/files/11987100/build.txt)

**Comment by edmonds** [comment]
OK, just reverted the CMake experiments, let's merge this branch and deal with the CMake stuff separately.

**Comment by jmckenna** [comment]
@edmonds the same error happens with today's `next` branch, on Windows, with MSVC:
```
CMakeFiles\protoc-gen-c.dir\build.make(405) : fatal error U1033: syntax error : '::' unexpected
```
which refers to these lines in the generated build.cmake
```
protoc-gen-c.exe: protobuf::libprotoc-NOTFOUND
protoc-gen-c.exe: protobuf::libprotobuf-NOTFOUND
```
This is with protobuf 24.3

I take it that I should go back to using protobuf-3.19.4 with protobuf-1.4.1 until all this is resolved (?).  Let me know if I can test more, or a different branch...

**Comment by jmckenna** [comment]
ah ok!  With the `next` branch I can now get past that error (!), in fact it was because cmake was trying to execute `protoc.exe` but there was a missing dll, FIXED! 

Ok, phew ha.

Now, cmake stops as it can't find `absl/strings` to include (as protobuf 24.3 requires ABSL).  Unfortunately I've tried to specify `-Dabsl_DIR` through cmake, but it isn't being leveraged.  Does the `next` branch include support for finding ABSL in `CMakeLists.txt` somehow?

For now, ugly, but I can copy/paste all of the absl/strings files into the protobuf-c/build-cmake/build/ folder,  and the compile makes it all the way to the end, during the linker stage, and of course it can't find `12 unresolved externals` for ABSL.  I need a way to specify  `-Dabsl_DIR` , hmm...

Hope you are following me here ha.

**Comment by edmonds** [comment]
> Hope you are following me here ha.

Not really! All I know is that protobuf is a dependency of protobuf-c, and absl is a newly introduced dependency in recent versions of protobuf. So we don't use absl at all in protobuf-c (and we still support older non-absl versions of protobuf in protobuf-c), and I have no idea why problems between protobuf and absl are leaking out and breaking builds of protobuf-c and other software.

You might try contacting the protobuf developers at https://github.com/protocolbuffers/protobuf/issues and see if there's some "right" way to invoke things.

Have you tried applying the patch in https://github.com/protocolbuffers/protobuf/pull/13206 to your protobuf build? I don't really know what it does or what it fixes, and neither do the protobuf developers because they won't look at it without a CLA :smiley:

**Comment by jmckenna** [comment]
I can get it down to only 2 missing symbols (functions called by ABSL, but not exposed through its shared Windows dll).  Frustrating.  I even tried compiling ABSL `master` branch.

(but yes, I had to modify the `CMakelists.txt` in protobuf-c, to leverage the ABSL includes and libs, or else I'd get hundreds of errors of missing includes and functions)

I bet I would have to patch ABSL for these 2 missing exported functions/symbols, to get this working on Windows...

fun (not), ha

**Pull request merged**
